<?php
$title = 'Edit album';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
		<?= $this->formLabel($album) ?>
		<?= $this->formElement($album) ?>
		<?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
		<?= $this->formLabel($artist) ?>
		<?= $this->formElement($artist) ?>
		<?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
		<?= $this->formLabel($email) ?>
		<?= $this->formElement($email) ?>
		<?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();