<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="btn btn-primary" href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Email</th>
        <th class="text-center">Action</th>
    </tr>
	<?php foreach ($this->paginator as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td><?= $this->escapeHtml($album->email) ?></td>
            <td align="center">
                <a class="btn btn-warning" href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                &nbsp;
                <a class="btn btn-danger" onclick="return confirm('Are you sure to delete <?= $album->title;?>?');" href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
            </td>
        </tr>
	<?php endforeach; ?>
</table>

<?= $this->paginationControl(
// The paginator object:
	$this->paginator,
	// The scrolling style:
	'sliding',
	// The partial to use to render the control:
	'partial/paginator',
	// The route to link to when a user clicks a control link:
	['route' => 'album-list']
) ?>